language: node_js

node_js:
  - "5"
  - "4"

git:
  depth: 3

before_install:
  - npm set progress=false

before_script:
  - npm run init
  - npm run lint

after_success:
    - npm run upload:coverage
