environment:
  matrix:
    - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - ps: ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

build: off
