environment:
  matrix:
    - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - ps: npm run init
  - npm run lint
  - npm test

build: off
