environment:
  matrix:
    - nodejs_version: "5"

clone_folder: C:\projects\calamars

shallow_clone: true

clone_depth: 3

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run pretest
  - cp -R %APPVEYOR_BUILD_FOLDER%/dist/npm/src/lib %APPVEYOR_BUILD_FOLDER%/node_modules/lib
  - SET NODE_PATH=dist\npm\src
  - CALL node -e "console.log(process.env.NODE_PATH)"
  - npm run test:windows

build: off
